/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pengelolauangkaskosan.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Shorfana
 */
public class mainViewinputData extends javax.swing.JFrame {

    /**
     * Creates new form mainViewinputData
     */
    public mainViewinputData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnpenyajian1 = new javax.swing.JLabel();
        inputDataView2 = new com.pengelolauangkaskosan.view.InputDataView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnpenyajian1.setForeground(new java.awt.Color(153, 0, 153));
        btnpenyajian1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exitataulogout.png"))); // NOI18N
        btnpenyajian1.setText("Log Out");
        btnpenyajian1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpenyajian1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpenyajian1MouseClicked(evt);
            }
        });
        getContentPane().add(btnpenyajian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));
        getContentPane().add(inputDataView2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpenyajian1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpenyajian1MouseClicked
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin akan "
                + "logout", "Peringatan", dialogBtn);

        if (dialogResult == 0) {
            this.setVisible(false);
            Login n = new Login();
            n.setVisible(true);
        } else {
            // false condition
        }
    }//GEN-LAST:event_btnpenyajian1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainViewinputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainViewinputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainViewinputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainViewinputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainViewinputData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnpenyajian1;
    private com.pengelolauangkaskosan.view.InputDataView inputDataView2;
    // End of variables declaration//GEN-END:variables
}
