/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pengelolauangkaskosan.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Idham Rahadian
 */
public class PanelInputData extends javax.swing.JPanel {

    /**
     * Creates new form PanelInputData
     */
    public PanelInputData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNominal = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        combNoLantai = new javax.swing.JComboBox<>();
        combNoKamar = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(207, 240, 158));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(121, 189, 154));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(11, 72, 107));
        jLabel1.setText("Input Data Penghuni");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 580, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(11, 72, 107));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 40, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(11, 72, 107));
        jLabel3.setText("Nominal");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(11, 72, 107));
        jLabel4.setText("Nama");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(11, 72, 107));
        jLabel5.setText("No Kamar");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(11, 72, 107));
        jLabel6.setText("No Lantai");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        txtNominal.setBackground(new java.awt.Color(207, 240, 158));
        txtNominal.setForeground(new java.awt.Color(11, 72, 107));
        txtNominal.setBorder(null);
        add(txtNominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 160, -1));

        txtNama.setBackground(new java.awt.Color(207, 240, 158));
        txtNama.setForeground(new java.awt.Color(11, 72, 107));
        txtNama.setBorder(null);
        add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 160, -1));

        combNoLantai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        add(combNoLantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        combNoKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        combNoKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combNoKamarActionPerformed(evt);
            }
        });
        add(combNoKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel7.setForeground(new java.awt.Color(11, 72, 107));
        jLabel7.setText("Rp.");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, 20));

        btnSimpan.setBackground(new java.awt.Color(59, 175, 79));
        btnSimpan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(11, 72, 107));
        btnSimpan.setText("Simpan");
        add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 433, 160, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 160, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin akan "
                + "keluar", "Peringatan", dialogBtn);

        if (dialogResult == 0) {
            // true condition
            System.exit(0);
        } else {
            // false condition
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void combNoKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combNoKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combNoKamarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> combNoKamar;
    private javax.swing.JComboBox<String> combNoLantai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNominal;
    // End of variables declaration//GEN-END:variables
}
