/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pengelolauangkaskosan.view;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Idham Rahadian
 */
public class PanelSignIn extends javax.swing.JPanel {

    /**
     * Creates new form SignPanel
     */
    public PanelSignIn() {
        initComponents();
        PanelOverlay.setBackground(new Color(0, 0, 0, 200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        PanelSignIn = new javax.swing.JPanel();
        txtNama = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();
        PanelSignUp = new javax.swing.JPanel();
        txtDaftarNama = new javax.swing.JTextField();
        txtDaftarPass = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtDaftarEmail = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        PanelOverlay = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMain.setBackground(new java.awt.Color(54, 70, 93));
        PanelMain.setLayout(new java.awt.CardLayout());

        PanelSignIn.setBackground(new java.awt.Color(54, 70, 93));
        PanelSignIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNama.setBackground(new java.awt.Color(54, 70, 93));
        txtNama.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setBorder(null);
        txtNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaFocusGained(evt);
            }
        });
        PanelSignIn.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 236, -1));

        txtPass.setBackground(new java.awt.Color(54, 70, 93));
        txtPass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setText("jPasswordField1");
        txtPass.setBorder(null);
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
        });
        PanelSignIn.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 236, -1));

        jSeparator1.setBackground(new java.awt.Color(28, 163, 51));
        jSeparator1.setForeground(new java.awt.Color(174, 181, 203));
        PanelSignIn.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 240, -1));

        jSeparator2.setBackground(new java.awt.Color(28, 163, 51));
        jSeparator2.setForeground(new java.awt.Color(174, 181, 203));
        PanelSignIn.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 240, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(174, 181, 203));
        jLabel4.setText("Jika Anda belum memiliki akun. Klik ");
        PanelSignIn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(28, 163, 51));
        jLabel5.setText("Sign up");
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        PanelSignIn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 265, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(28, 163, 51));
        jLabel8.setText("Nama ");
        PanelSignIn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(174, 181, 203));
        jLabel2.setText(" X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        PanelSignIn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(28, 163, 51));
        jLabel3.setText("Password");
        PanelSignIn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        btnSignIn.setBackground(new java.awt.Color(28, 163, 51));
        btnSignIn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnSignIn.setForeground(new java.awt.Color(255, 255, 255));
        btnSignIn.setText("Sign in");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        PanelSignIn.add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 240, 40));

        PanelMain.add(PanelSignIn, "card12");

        PanelSignUp.setBackground(new java.awt.Color(54, 70, 93));
        PanelSignUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDaftarNama.setBackground(new java.awt.Color(54, 70, 93));
        txtDaftarNama.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtDaftarNama.setForeground(new java.awt.Color(255, 255, 255));
        txtDaftarNama.setBorder(null);
        txtDaftarNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDaftarNamaFocusGained(evt);
            }
        });
        PanelSignUp.add(txtDaftarNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 236, -1));

        txtDaftarPass.setBackground(new java.awt.Color(54, 70, 93));
        txtDaftarPass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtDaftarPass.setForeground(new java.awt.Color(255, 255, 255));
        txtDaftarPass.setText("jPasswordField1");
        txtDaftarPass.setBorder(null);
        txtDaftarPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDaftarPassFocusGained(evt);
            }
        });
        PanelSignUp.add(txtDaftarPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 236, -1));

        jSeparator3.setBackground(new java.awt.Color(28, 163, 51));
        jSeparator3.setForeground(new java.awt.Color(174, 181, 203));
        PanelSignUp.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 240, -1));

        jSeparator4.setBackground(new java.awt.Color(28, 163, 51));
        jSeparator4.setForeground(new java.awt.Color(174, 181, 203));
        PanelSignUp.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 240, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(174, 181, 203));
        jLabel9.setText("Jika Anda sudah memiliki akun. Klik");
        PanelSignUp.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(28, 163, 51));
        jLabel10.setText("Sign in");
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        PanelSignUp.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 349, -1, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(28, 163, 51));
        jLabel11.setText("Nama ");
        PanelSignUp.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(174, 181, 203));
        jLabel12.setText(" X");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        PanelSignUp.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(174, 181, 203));
        jLabel13.setText("Password");
        PanelSignUp.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        btnSignUp.setBackground(new java.awt.Color(28, 163, 51));
        btnSignUp.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        PanelSignUp.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 240, 40));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(174, 181, 203));
        jLabel14.setText("Email");
        PanelSignUp.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        txtDaftarEmail.setBackground(new java.awt.Color(54, 70, 93));
        txtDaftarEmail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtDaftarEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtDaftarEmail.setBorder(null);
        txtDaftarEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDaftarEmailFocusGained(evt);
            }
        });
        PanelSignUp.add(txtDaftarEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 236, -1));

        jSeparator5.setBackground(new java.awt.Color(28, 163, 51));
        jSeparator5.setForeground(new java.awt.Color(174, 181, 203));
        PanelSignUp.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 240, -1));

        PanelMain.add(PanelSignUp, "card3");

        add(PanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 370, 420));

        PanelOverlay.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pengelolauangkaskosan/icon/iconApp.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Aplikasi Manajemen Uang Kas Kostan");

        javax.swing.GroupLayout PanelOverlayLayout = new javax.swing.GroupLayout(PanelOverlay);
        PanelOverlay.setLayout(PanelOverlayLayout);
        PanelOverlayLayout.setHorizontalGroup(
            PanelOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOverlayLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(PanelOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOverlayLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOverlayLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(96, 96, 96))))
        );
        PanelOverlayLayout.setVerticalGroup(
            PanelOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOverlayLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        add(PanelOverlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pengelolauangkaskosan/icon/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:

        setBackground(Color.BLACK);

    }//GEN-LAST:event_btnSignInActionPerformed

    private void txtNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusGained
        // TODO add your handling code here:
        jSeparator1.setBackground(new Color(174, 181, 203));
        jLabel3.setForeground(new Color(174, 181, 203));
        jSeparator2.setBackground(new Color(28, 163, 51));
        jLabel8.setForeground(new Color(28, 163, 51));
    }//GEN-LAST:event_txtNamaFocusGained

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin akan "
                + "keluar", "Peringatan", dialogBtn);

        if (dialogResult == 0) {
            // true condition
            System.exit(0);
        } else {
            // false condition
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        // TODO add your handling code here:
        jSeparator2.setBackground(new Color(174, 181, 203));
        jLabel8.setForeground(new Color(174, 181, 203));
        jSeparator1.setBackground(new Color(28, 163, 51));
        jLabel3.setForeground(new Color(28, 163, 51));
    }//GEN-LAST:event_txtPassFocusGained

    private void txtDaftarNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDaftarNamaFocusGained
        // TODO add your handling code here:
        jSeparator5.setBackground(new Color(174, 181, 203));
        jLabel14.setForeground(new Color(174, 181, 203));
        jSeparator3.setBackground(new Color(174, 181, 203));
        jLabel13.setForeground(new Color(174, 181, 203));
        jSeparator4.setBackground(new Color(28, 163, 51));
        jLabel11.setForeground(new Color(28, 163, 51));
    }//GEN-LAST:event_txtDaftarNamaFocusGained

    private void txtDaftarPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDaftarPassFocusGained
        // TODO add your handling code here:
        jSeparator5.setBackground(new Color(174, 181, 203));
        jLabel14.setForeground(new Color(174, 181, 203));
        jSeparator4.setBackground(new Color(174, 181, 203));
        jLabel11.setForeground(new Color(174, 181, 203));
        jSeparator3.setBackground(new Color(28, 163, 51));
        jLabel13.setForeground(new Color(28, 163, 51));
    }//GEN-LAST:event_txtDaftarPassFocusGained

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin akan "
                + "keluar", "Peringatan", dialogBtn);

        if (dialogResult == 0) {
            // true condition
            System.exit(0);
        } else {
            // false condition
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void txtDaftarEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDaftarEmailFocusGained
        // TODO add your handling code here:
        jSeparator4.setBackground(new Color(174, 181, 203));
        jLabel11.setForeground(new Color(174, 181, 203));
        jSeparator3.setBackground(new Color(174, 181, 203));
        jLabel13.setForeground(new Color(174, 181, 203));
        jSeparator5.setBackground(new Color(28, 163, 51));
        jLabel14.setForeground(new Color(28, 163, 51));
    }//GEN-LAST:event_txtDaftarEmailFocusGained

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        // Remove all panel
        PanelMain.removeAll();
        PanelMain.repaint();
        PanelMain.revalidate();

        // Add panel
        PanelMain.add(PanelSignIn);
        PanelMain.repaint();
        PanelMain.revalidate();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        // Remove all panel
        PanelMain.removeAll();
        PanelMain.repaint();
        PanelMain.revalidate();

        // Add panel
        PanelMain.add(PanelSignUp);
        PanelMain.repaint();
        PanelMain.revalidate();
    }//GEN-LAST:event_jLabel5MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelOverlay;
    private javax.swing.JPanel PanelSignIn;
    private javax.swing.JPanel PanelSignUp;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField txtDaftarEmail;
    private javax.swing.JTextField txtDaftarNama;
    private javax.swing.JPasswordField txtDaftarPass;
    private javax.swing.JTextField txtNama;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
